//! # Weight Info for Pallet AI Chat
//!
//! Autogenerated weights for pallet_ai_chat

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_ai_chat.
pub trait WeightInfo {
    fn create_conversation() -> Weight;
    fn send_message() -> Weight;
    fn update_conversation_status() -> Weight;
    fn rate_message() -> Weight;
    fn update_personality_config() -> Weight;
    fn add_api_config() -> Weight;
    fn update_api_config() -> Weight;
    fn submit_ocw_response() -> Weight;
}

/// Weights for pallet_ai_chat using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_conversation() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn send_message() -> Weight {
        Weight::from_parts(20_000, 0)
    }
    fn update_conversation_status() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn rate_message() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn update_personality_config() -> Weight {
        Weight::from_parts(15_000, 0)
    }
    fn add_api_config() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn update_api_config() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn submit_ocw_response() -> Weight {
        Weight::from_parts(30_000, 0)
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_conversation() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn send_message() -> Weight {
        Weight::from_parts(20_000, 0)
    }
    fn update_conversation_status() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn rate_message() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn update_personality_config() -> Weight {
        Weight::from_parts(15_000, 0)
    }
    fn add_api_config() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn update_api_config() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn submit_ocw_response() -> Weight {
        Weight::from_parts(30_000, 0)
    }
}
