[package]
name = "pallet-otc-listing"
version = "0.1.0"
license = "MIT-0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"], default-features = false }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
pallet-balances = { workspace = true }
pallet-otc-maker = { path = "../otc-maker", default-features = false }
pallet-escrow = { path = "../escrow", default-features = false }
pallet-pricing = { path = "../pricing", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-std/std",
    "pallet-balances/std",
    "pallet-otc-maker/std",
    "pallet-escrow/std",
    "pallet-pricing/std",
]


