//! Autogenerated weights for pallet_contacts
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-01-21
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `substrate-node`, CPU: `Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_contacts
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./pallets/contacts/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_contacts.
pub trait WeightInfo {
	fn add_contact() -> Weight;
	fn remove_contact() -> Weight;
	fn update_contact() -> Weight;
	fn create_group() -> Weight;
	fn delete_group() -> Weight;
	fn rename_group() -> Weight;
	fn block_account() -> Weight;
	fn unblock_account() -> Weight;
	fn send_friend_request() -> Weight;
	fn accept_friend_request() -> Weight;
	fn reject_friend_request() -> Weight;
}

/// Weights for pallet_contacts using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Contacts Contacts (r:2 w:1)
	/// Proof: Contacts Contacts (max_values: None, max_size: Some(1024), added: 3024, mode: MaxEncodedLen)
	/// Storage: Contacts ContactCount (r:1 w:1)
	/// Proof: Contacts ContactCount (max_values: None, max_size: Some(20), added: 520, mode: MaxEncodedLen)
	/// Storage: Contacts Blacklist (r:1 w:0)
	/// Proof: Contacts Blacklist (max_values: None, max_size: Some(512), added: 2512, mode: MaxEncodedLen)
	/// Storage: Contacts Groups (r:10 w:0)
	/// Proof: Contacts Groups (max_values: None, max_size: Some(256), added: 2560, mode: MaxEncodedLen)
	/// Storage: Contacts GroupMembers (r:10 w:10)
	/// Proof: Contacts GroupMembers (max_values: None, max_size: Some(4096), added: 8192, mode: MaxEncodedLen)
	fn add_contact() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(24))
			.saturating_add(T::DbWeight::get().writes(12))
	}

	/// Storage: Contacts Contacts (r:2 w:2)
	/// Proof: Contacts Contacts (max_values: None, max_size: Some(1024), added: 3024, mode: MaxEncodedLen)
	/// Storage: Contacts ContactCount (r:1 w:1)
	/// Proof: Contacts ContactCount (max_values: None, max_size: Some(20), added: 520, mode: MaxEncodedLen)
	/// Storage: Contacts GroupMembers (r:10 w:10)
	/// Proof: Contacts GroupMembers (max_values: None, max_size: Some(4096), added: 8192, mode: MaxEncodedLen)
	/// Storage: Contacts Groups (r:10 w:10)
	/// Proof: Contacts Groups (max_values: None, max_size: Some(256), added: 2560, mode: MaxEncodedLen)
	fn remove_contact() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(23))
			.saturating_add(T::DbWeight::get().writes(23))
	}

	/// Storage: Contacts Contacts (r:1 w:1)
	/// Proof: Contacts Contacts (max_values: None, max_size: Some(1024), added: 3024, mode: MaxEncodedLen)
	/// Storage: Contacts Groups (r:20 w:0)
	/// Proof: Contacts Groups (max_values: None, max_size: Some(256), added: 2560, mode: MaxEncodedLen)
	/// Storage: Contacts GroupMembers (r:20 w:20)
	/// Proof: Contacts GroupMembers (max_values: None, max_size: Some(4096), added: 8192, mode: MaxEncodedLen)
	fn update_contact() -> Weight {
		Weight::from_parts(55_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(41))
			.saturating_add(T::DbWeight::get().writes(21))
	}

	/// Storage: Contacts Groups (r:1 w:1)
	/// Proof: Contacts Groups (max_values: None, max_size: Some(256), added: 2560, mode: MaxEncodedLen)
	/// Storage: Contacts GroupMembers (r:0 w:1)
	/// Proof: Contacts GroupMembers (max_values: None, max_size: Some(4096), added: 8192, mode: MaxEncodedLen)
	fn create_group() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: Contacts Groups (r:1 w:1)
	/// Proof: Contacts Groups (max_values: None, max_size: Some(256), added: 2560, mode: MaxEncodedLen)
	/// Storage: Contacts GroupMembers (r:1 w:1)
	/// Proof: Contacts GroupMembers (max_values: None, max_size: Some(4096), added: 8192, mode: MaxEncodedLen)
	/// Storage: Contacts Contacts (r:100 w:100)
	/// Proof: Contacts Contacts (max_values: None, max_size: Some(1024), added: 3024, mode: MaxEncodedLen)
	fn delete_group() -> Weight {
		Weight::from_parts(80_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(102))
			.saturating_add(T::DbWeight::get().writes(102))
	}

	/// Storage: Contacts Groups (r:2 w:2)
	/// Proof: Contacts Groups (max_values: None, max_size: Some(256), added: 2560, mode: MaxEncodedLen)
	/// Storage: Contacts GroupMembers (r:2 w:2)
	/// Proof: Contacts GroupMembers (max_values: None, max_size: Some(4096), added: 8192, mode: MaxEncodedLen)
	/// Storage: Contacts Contacts (r:100 w:100)
	/// Proof: Contacts Contacts (max_values: None, max_size: Some(1024), added: 3024, mode: MaxEncodedLen)
	fn rename_group() -> Weight {
		Weight::from_parts(85_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(104))
			.saturating_add(T::DbWeight::get().writes(104))
	}

	/// Storage: Contacts Blacklist (r:1 w:1)
	/// Proof: Contacts Blacklist (max_values: None, max_size: Some(512), added: 2512, mode: MaxEncodedLen)
	/// Storage: Contacts Contacts (r:1 w:1)
	/// Proof: Contacts Contacts (max_values: None, max_size: Some(1024), added: 3024, mode: MaxEncodedLen)
	/// Storage: Contacts ContactCount (r:1 w:1)
	/// Proof: Contacts ContactCount (max_values: None, max_size: Some(20), added: 520, mode: MaxEncodedLen)
	/// Storage: Contacts GroupMembers (r:10 w:10)
	/// Proof: Contacts GroupMembers (max_values: None, max_size: Some(4096), added: 8192, mode: MaxEncodedLen)
	/// Storage: Contacts Groups (r:10 w:10)
	/// Proof: Contacts Groups (max_values: None, max_size: Some(256), added: 2560, mode: MaxEncodedLen)
	fn block_account() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(23))
			.saturating_add(T::DbWeight::get().writes(23))
	}

	/// Storage: Contacts Blacklist (r:1 w:1)
	/// Proof: Contacts Blacklist (max_values: None, max_size: Some(512), added: 2512, mode: MaxEncodedLen)
	fn unblock_account() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Contacts Blacklist (r:1 w:0)
	/// Proof: Contacts Blacklist (max_values: None, max_size: Some(512), added: 2512, mode: MaxEncodedLen)
	/// Storage: Contacts FriendRequests (r:1 w:1)
	/// Proof: Contacts FriendRequests (max_values: None, max_size: Some(48), added: 1024, mode: MaxEncodedLen)
	/// Storage: Contacts Contacts (r:1 w:0)
	/// Proof: Contacts Contacts (max_values: None, max_size: Some(1024), added: 3024, mode: MaxEncodedLen)
	fn send_friend_request() -> Weight {
		Weight::from_parts(18_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Contacts FriendRequests (r:1 w:1)
	/// Proof: Contacts FriendRequests (max_values: None, max_size: Some(48), added: 1024, mode: MaxEncodedLen)
	/// Storage: Contacts Blacklist (r:1 w:0)
	/// Proof: Contacts Blacklist (max_values: None, max_size: Some(512), added: 2512, mode: MaxEncodedLen)
	/// Storage: Contacts ContactCount (r:1 w:1)
	/// Proof: Contacts ContactCount (max_values: None, max_size: Some(20), added: 520, mode: MaxEncodedLen)
	/// Storage: Contacts Contacts (r:2 w:2)
	/// Proof: Contacts Contacts (max_values: None, max_size: Some(1024), added: 3024, mode: MaxEncodedLen)
	fn accept_friend_request() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}

	/// Storage: Contacts FriendRequests (r:1 w:1)
	/// Proof: Contacts FriendRequests (max_values: None, max_size: Some(48), added: 1024, mode: MaxEncodedLen)
	fn reject_friend_request() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn add_contact() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(24))
			.saturating_add(RocksDbWeight::get().writes(12))
	}

	fn remove_contact() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(23))
			.saturating_add(RocksDbWeight::get().writes(23))
	}

	fn update_contact() -> Weight {
		Weight::from_parts(55_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(41))
			.saturating_add(RocksDbWeight::get().writes(21))
	}

	fn create_group() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(2))
	}

	fn delete_group() -> Weight {
		Weight::from_parts(80_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(102))
			.saturating_add(RocksDbWeight::get().writes(102))
	}

	fn rename_group() -> Weight {
		Weight::from_parts(85_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(104))
			.saturating_add(RocksDbWeight::get().writes(104))
	}

	fn block_account() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(23))
			.saturating_add(RocksDbWeight::get().writes(23))
	}

	fn unblock_account() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn send_friend_request() -> Weight {
		Weight::from_parts(18_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn accept_friend_request() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}

	fn reject_friend_request() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}

use frame_support::weights::constants::RocksDbWeight;
