//! # Weight Info for Pallet Deceased AI
//!
//! Autogenerated weights for pallet_deceased_ai
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: [Placeholder]
//!
//! STEPS: `50`, REPEAT: `20`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_deceased_ai.
pub trait WeightInfo {
    fn register_ai_provider() -> Weight;
    fn update_quota() -> Weight;
    fn verify_provider() -> Weight;
    fn query_training_data() -> Weight;
    fn export_training_dataset() -> Weight;
    fn create_training_task() -> Weight;
    fn update_task_status() -> Weight;
    fn register_ai_agent() -> Weight;
    fn update_agent_status() -> Weight;
}

/// Weights for pallet_deceased_ai using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn register_ai_provider() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn update_quota() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn verify_provider() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn query_training_data() -> Weight {
        Weight::from_parts(20_000, 0)
    }
    fn export_training_dataset() -> Weight {
        Weight::from_parts(50_000, 0)
    }
    fn create_training_task() -> Weight {
        Weight::from_parts(30_000, 0)
    }
    fn update_task_status() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn register_ai_agent() -> Weight {
        Weight::from_parts(20_000, 0)
    }
    fn update_agent_status() -> Weight {
        Weight::from_parts(10_000, 0)
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn register_ai_provider() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn update_quota() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn verify_provider() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn query_training_data() -> Weight {
        Weight::from_parts(20_000, 0)
    }
    fn export_training_dataset() -> Weight {
        Weight::from_parts(50_000, 0)
    }
    fn create_training_task() -> Weight {
        Weight::from_parts(30_000, 0)
    }
    fn update_task_status() -> Weight {
        Weight::from_parts(10_000, 0)
    }
    fn register_ai_agent() -> Weight {
        Weight::from_parts(20_000, 0)
    }
    fn update_agent_status() -> Weight {
        Weight::from_parts(10_000, 0)
    }
}
