name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    name: Rust fmt/clippy/test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system deps (llvm/clang)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            clang llvm-dev libclang-dev pkg-config build-essential

      - name: Setup Rust toolchain (from rust-toolchain.toml)
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: cargo fmt --check
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: cargo test
        run: cargo test --workspace --all-features -q

  dapp:
    name: Build memopark-dapp
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: memopark-dapp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: memopark-dapp/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present

name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/free-disk-space
      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/ubuntu-dependencies
      - if: contains(matrix.os, 'macos')
        uses: ./.github/actions/macos-dependencies

      - name: Build the template
        run: cargo build
        timeout-minutes: 90

      - name: Run clippy
        run: |
          SKIP_WASM_BUILD=1 cargo clippy --all-targets --locked --workspace --quiet
          SKIP_WASM_BUILD=1 cargo clippy --all-targets --all-features --locked --workspace --quiet
        timeout-minutes: 30

      - name: Run the tests
        run: SKIP_WASM_BUILD=1 cargo test
        timeout-minutes: 15

      - name: Build the docs
        run: SKIP_WASM_BUILD=1 cargo doc --workspace --no-deps
        timeout-minutes: 15

  run-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/free-disk-space
      - if: contains(matrix.os, 'ubuntu')
        uses: ./.github/actions/ubuntu-dependencies
      - if: contains(matrix.os, 'macos')
        uses: ./.github/actions/macos-dependencies

      - name: Build the node individually in release mode
        run: cargo build --package solochain-template-node --release
        timeout-minutes: 90

      - name: Make sure the node is producing blocks
        run: |
          ./target/release/solochain-template-node --dev 2>&1 | tee out.txt &
          until curl -s '127.0.0.1:9944'; do sleep 5; done
          until cat out.txt | grep -s "Imported #2"; do sleep 5; done
        shell: bash
        timeout-minutes: 5

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/free-disk-space

      - name: Build the Dockerfile
        run: docker build . -t polkadot-sdk-solochain-template
        timeout-minutes: 90
